title: Asif Arefin Bonny Resume & Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "."
  Personal resume and blog site for Asif Arefin Bonny.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown 